[package]
name = "tiny-cache"
version = "0.1.0"
authors = ["Michael Matuzak <mmatuzak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "0.99.3"
futures-preview = "0.2.2"
